### ISSUE TITLE
Allow R_xlen_t start and end rows

### ISSUE THREAD

**Issue by dipterix** [fstpackage/fstcore#3]
https://github.com/fstpackage/fstcore/blob/d5a7481d1bdf96af5804a20e21e985a76613e7cd/src/flex_store.cpp#L233

Hi, Mark,I found one issue when partially loading data frame that has nrows >= 2^31. In R, `INTEGER()` only supports maximum integer of 2^31-1 (~18GB * # of column). However, `R_xlen_t` is way beyond that on x64 architecture. 

In your `FstStore::fstRead` definition,`startRow` and  `endRow` allow `long long`, which (I think) is the definition of `R_xlen_t`, and has limit of `2^63-1`.

```cpp
FstStore::fstRead(IFstTable &tableReader, IStringArray* columnSelection, const long long startRow, const long long endRow,
  IColumnFactory* columnFactory, vector<int> &keyIndex, IStringArray* selectedCols, IStringColumn* col_names)
```

For example, the following code can break the limit of INTEGER()

```r
f=tempfile()
fst::write_fst(structure(list(V1=1:(2^31+1)), class = 'data.frame', row.names = c(NA, -1L)), path = f)
.Call(fstcore:::`_fstcore_fstretrieve`, normalizePath(f), "V1", as.integer(2^31-10), 2^31+1)
```

However, setting `endRow` be `NULL` allows me to read the final lines.

```
.Call(fstcore:::`_fstcore_fstretrieve`, normalizePath(f), "V1", as.integer(2^31-10), NULL)
```

Best.

**Comment by MarcusKlik** [comment]
Hi @dipterix, thanks for reporting. Yes, the `fstlib` library can handle 64 bit ranges but the `fst` API is not able to use that yet. That should definitely be fixed in the next release!

**Comment by dipterix** [comment]
Great to hear that!

Also I have an irrelevant issue encountered recently. I forked your package and made some experiments on the forked version. I found my R keeps crashing when I use `devtools::load_all()` or sometimes recompiling in RStudio.

Did you have any similar experience before? I posted an issue here: https://github.com/r-lib/devtools/issues/2277

Basically OpenMP causes this issue, but it's interesting to me that `parallel` or `future` package forked clusters worked fine. So I guess users will still use packages fine, but it's really annoying to devs.

**Comment by MarcusKlik** [comment]
Hi @dipterix, thanks for reporting. Let me get this straight :-) So if you compile the `dev` version of `fstcore` and then load it using `library()` it's fine, but when you use `devtools::load_all()` it crashes the (current) session?

**Comment by dipterix** [comment]
It requires some steps to reproduce

1. compile & load package
2. Run some R code that eventually runs OpenMP
3. change cpp scripts (add lines or delete lines, any change)
4. call `devtools::load_all()`

Step 2 is required to reproduce this issue. If step 2 is missing, either works, but if step 2 is present, load_all just crash R session. 

I disabled OpenMP and it just worked fine. So I guess either `devtools` is bugged with OpenMP, or OpenMP was not properly turned off when running `load_all`.

**Comment by MarcusKlik** [comment]
Hi @dipterix, using row selectors with values larger than 2^31 now works with `fstcore`:

``` r
# manually create a data frame with a 'long' column
df <- structure(
  list(
    X = rep(as.raw(1L), 2^31 + 1)
  ),
  class = "data.frame")


# column is indeed a long vec
length(df$X) > 2^31
#> [1] TRUE


# write to disk
path <- tempfile(fileext = ".fst")
fst::write_fst(df, path)


# read from disk with latest fst from CRAN
y <- fst::read_fst(path)

# a list is returned
str(y)
#> List of 1
#>  $ X: raw [1:2147483649] 01 01 01 01 ...


# does not work (yet)
y <- fst::read_fst(path, NULL, 1, 2^31 + 1)
#> Warning in fst::read_fst(path, NULL, 1, 2^31 + 1): NAs introduced by coercion to
#> integer range
#> Error in fst::read_fst(path, NULL, 1, 2^31 + 1): Incorrect row range specified.


# works now
y <- fstcore:::fstretrieve(path, NULL, 1, 2^31 + 1)

# a list is returned as expected
str(y)
#> List of 3
#>  $ keyNames: chr(0) 
#>  $ keyIndex: int(0) 
#>  $ resTable:List of 1
#>   ..$ X: raw [1:2147483649] 01 01 01 01 ...
```

**Comment by dipterix** [comment]
Thanks for the prompt solution! This is really helpful.
