### ISSUE TITLE
`liblz4 was not found` error, which did not occur yesterday, occurred today when source installation of fst

### ISSUE THREAD

**Issue by eitsupi** [fstpackage/fstcore#7]
Hello. Thank you for your continued development.

The following error occurred during source installation of the `fstcore` package on Ubuntu today.

```log
#6 1783.9 * installing *source* package ‘fstcore’ ...
#6 1783.9 ** package ‘fstcore’ successfully unpacked and MD5 sums checked
#6 1783.9 ** using staged installation
#6 1783.9 0.29.1
#6 1783.9 Package liblz4 was not found in the pkg-config search path.
#6 1783.9 Perhaps you should add the directory containing `liblz4.pc'
#6 1783.9 to the PKG_CONFIG_PATH environment variable
#6 1783.9 No package 'liblz4' found
#6 1783.9 Package liblz4 was not found in the pkg-config search path.
#6 1783.9 Perhaps you should add the directory containing `liblz4.pc'
#6 1783.9 to the PKG_CONFIG_PATH environment variable
#6 1783.9 No package 'liblz4' found
#6 1783.9 Using PKG_CFLAGS= and PKG_LIBS=-llz4
#6 1783.9 ------------------------- ANTICONF ERROR ---------------------------
#6 1783.9 Configuration failed because liblz4 was not found. Try installing:
#6 1783.9  * deb: liblz4-dev (Debian, Ubuntu, etc)
#6 1783.9  * rpm: liblz4-devel (Fedora, CentOS, RHEL)
#6 1783.9  * csw: liblz4_dev (Solaris)
#6 1783.9  * OSX: lz4 (macOS)
#6 1783.9 If liblz4 is already installed, check that 'pkg-config' is in your
#6 1783.9 PATH and PKG_CONFIG_PATH contains a liblz4.pc file. If pkg-config
#6 1783.9 is unavailable you can set INCLUDE_LZ4_DIR and LIB_LZ4_DIR manually via:
#6 1783.9 R CMD INSTALL --configure-vars='INCLUDE_LZ4_DIR=... LIB_LZ4_DIR=...'
#6 1783.9 Alternatively, you can build the required libraries directly from bundled code by
#6 1783.9 setting BUILD_INTERNAL_LIBS to true
#6 1783.9 --------------------------------------------------------------------
#6 1783.9 ERROR: configuration failed for package ‘fstcore’
```

This is the build log of `rocker/tidyverse:devel`, [which is built on time every day](https://github.com/rocker-org/rocker-versioned2/actions/workflows/devel.yml).

`liblz4-1` is already installed on this image.
I am wondering if the error is due to the new `fstcore` version 0.9.10 no longer finding `liblz4-1` or if I need to add `liblz4-dev` as a new dependency.

**Comment by MarcusKlik** [comment]
Hi @eitsupi, thanks for reporting the problem!

on request of CRAN, the package now checks for installed versions of `LZ4`. The configure script runs

``` shell
pkg-config --libs liblz4
```

to determine the location of the library. If I remove `liblz4-devel` and install only `liblz4-1` on an Ubuntu machine, `pkg-config` does not see `LZ4` anymore, as you also see on your system.

If I'm correct, `liblz4-1` is the runtime variant of `LZ4`, so without header files.
So I think indeed you require the _dev_ version for the build to succeed.

To avoid broken builds, I think `fstcore` needs a fallback where the included code is compiled upon failure to locate `LZ4`!

**Comment by sclewis23** [comment]
I thought if fstcore can't find liblz4 library installed, it would compiling code directly from the package sources?

**Comment by MarcusKlik** [comment]
Hi @sclewis23, thanks for your question. I just submitted a new version of `fstcore` to CRAN that compiles the bundled code in case it can't find `liblz4` or `libzstd`. In the meantime, you can also force the (current) package to build the included `LZ4` and `ZSTD` code by setting `BUILD_INTERNAL_LIBS=true` before building, e.g.:

``` shell
 R CMD INSTALL --configure-vars='BUILD_INTERNAL_LIBS=true'
```

hope that helps until the new version is available on CRAN!

**Comment by benz0li** [comment]
@MarcusKlik Thank you for the quick fix.

**Comment by MarcusKlik** [comment]
@benz0li, you're welcome, `fstcore` v0.9.12 is on CRAN now :-)

**Comment by eitsupi** [comment]
Thank you for very quick update!
